// src/screens/GameArena/styles/GameArenaStyles.js
import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export default StyleSheet.create({
  container: { padding: 16, backgroundColor: '#f8fafc', flexGrow: 1, paddingBottom: 60 },
  darkContainer: { backgroundColor: '#0f172a' },
  darkCard: { backgroundColor: '#1e293b', borderColor: '#334155' },
  darkText: { color: '#f8fafc' },
  darkInput: { backgroundColor: '#0f172a', borderColor: '#334155', color: '#f8fafc' },
  sponsorBanner: { backgroundColor: '#fefcbf', padding: 10, borderRadius: 8, marginBottom: 12, borderWidth: 1, borderColor: '#d69e2e', alignItems: 'center' },
  gameTabRow: { flexDirection: 'row', backgroundColor: '#e2e8f0', borderRadius: 8, padding: 4, marginBottom: 12 },
  gameTabBtn: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 6 },
  activeGameTab: { backgroundColor: '#ffffff', elevation: 2 },
  gameTabText: { fontSize: 12, fontWeight: '600', color: '#64748b' },
  activeGameTabText: { color: '#2563eb', fontWeight: '700' },
  card: { backgroundColor: '#ffffff', borderRadius: 12, padding: 12, marginBottom: 12, borderWidth: 1, borderColor: '#e2e8f0' },
  boardCard: { backgroundColor: '#ffffff', borderRadius: 12, padding: 14, borderWidth: 1, borderColor: '#e2e8f0', marginBottom: 12 },
  liveHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  liveBadge: { backgroundColor: '#dc2626', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  spectatorText: { fontSize: 11, fontWeight: '600', color: '#64748b' },
  broadcastMasterContainer: { marginBottom: 10, gap: 10 },
  hostSquareWrapper: { width: '100%', alignItems: 'center', marginBottom: 4 },
  hostSquareStreamBox: { width: '100%', height: 140, backgroundColor: '#0f172a', borderRadius: 10, position: 'relative', overflow: 'hidden', borderWidth: 2, borderColor: '#3b82f6' },
  hostLabelOverlay: { position: 'absolute', bottom: 4, left: 6, right: 6, backgroundColor: 'rgba(30, 58, 138, 0.9)', paddingVertical: 3, borderRadius: 6, alignItems: 'center' },
  squarePlayersGrid: { flexDirection: 'row', gap: 10, width: '100%' },
  competitorSquareColumn: { flex: 1 },
  squareCompetitorStreamBox: { width: '100%', height: 130, backgroundColor: '#0f172a', borderRadius: 10, position: 'relative', overflow: 'hidden', borderWidth: 2, borderColor: '#047857' },
  playerLabelOverlay: { position: 'absolute', bottom: 4, left: 4, right: 4, backgroundColor: 'rgba(6,95,70,0.85)', paddingVertical: 3, borderRadius: 6, alignItems: 'center' },
  cheerSectionBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#1e293b', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, marginTop: 4, borderWidth: 1, borderColor: '#334155' },
  cheerBoostBtn: { backgroundColor: '#d97706', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  centralGameTable: { backgroundColor: '#064e3b', borderRadius: 8, padding: 10, marginBottom: 10, borderWidth: 1, borderColor: '#047857', alignItems: 'center' },
  tableHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6, width: '100%' },
  physicalBoardContainer: { width: 240, height: 240, borderWidth: 2, borderColor: '#022c22', alignSelf: 'center', marginVertical: 4 },
  boardRow: { flexDirection: 'row', flex: 1 },
  boardSquare: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  lightSquare: { backgroundColor: '#f0d9b5' },
  darkSquare: { backgroundColor: '#b58863' },
  pieceText: { fontSize: 18, fontWeight: 'bold' },
  draftRedPiece: { width: 16, height: 16, borderRadius: 8, backgroundColor: '#dc2626', borderWidth: 1, borderColor: '#fff' },
  draftDarkPiece: { width: 16, height: 16, borderRadius: 8, backgroundColor: '#1e293b', borderWidth: 1, borderColor: '#94a3b8' },
  poolFeltContainer: { width: 260, height: 150, backgroundColor: '#047857', borderRadius: 8, borderWidth: 6, borderColor: '#022c22', alignSelf: 'center', marginVertical: 4, position: 'relative', overflow: 'hidden' },
  pocketMarker: { position: 'absolute', width: 12, height: 12, borderRadius: 6, backgroundColor: '#000000' },
  poolBallItem: { position: 'absolute', width: 16, height: 16, borderRadius: 8, justifyContent: 'center', alignItems: 'center', elevation: 3 },
  gameTableContent: { alignItems: 'center', paddingVertical: 4 },
  matatuCardItem: { backgroundColor: '#f8fafc', paddingHorizontal: 10, paddingVertical: 8, borderRadius: 4, borderWidth: 1, borderColor: '#cbd5e1' },
  actionButtonRow: { flexDirection: 'row', gap: 8, marginBottom: 10 },
  playActionBtn: { flex: 1, backgroundColor: '#3182ce', paddingVertical: 10, borderRadius: 6, alignItems: 'center' },
  tipRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#f1f5f9', paddingTop: 10 },
  tipLabel: { fontSize: 11, fontWeight: '600', color: '#334155' },
  tipBtn: { backgroundColor: '#eff6ff', borderWidth: 1, borderColor: '#3b82f6', paddingHorizontal: 8, paddingVertical: 5, borderRadius: 6 },
  tipBtnText: { color: '#2563eb', fontSize: 10, fontWeight: '700' },
  chatCard: { backgroundColor: '#ffffff', borderRadius: 12, padding: 14, borderWidth: 1, borderColor: '#e2e8f0', marginTop: 10 },
  chatHeaderTitle: { fontSize: 12, fontWeight: '700', color: '#0f172a', marginBottom: 8 },
  chatScroll: { height: 100, backgroundColor: '#f8fafc', borderRadius: 8, padding: 8, marginBottom: 18, borderWidth: 1, borderColor: '#e2e8f0' },
  chatMsgRow: { flexDirection: 'row', marginBottom: 4 },
  chatUser: { fontSize: 11, fontWeight: '700', color: '#2563eb' },
  chatText: { fontSize: 11, color: '#334155' },
  inputRow: { flexDirection: 'row' },
  input: { flex: 1, borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 8, paddingHorizontal: 10, height: 36, backgroundColor: '#f8fafc', fontSize: 11, color: '#0f172a', marginRight: 8 },
  sendBtn: { backgroundColor: '#2563eb', justifyContent: 'center', paddingHorizontal: 14, borderRadius: 8 },
  sendBtnText: { color: '#ffffff', fontSize: 11, fontWeight: '700' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  drawerContent: { backgroundColor: '#fff', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  wagerOptBtn: { flex: 1, backgroundColor: '#f7fafc', padding: 10, borderRadius: 8, alignItems: 'center', borderWidth: 1, borderColor: '#cbd5e0' },
  confirmWagerBtn: { backgroundColor: '#d69e2e', padding: 12, borderRadius: 8, alignItems: 'center' },
});